<Project Sdk="Microsoft.NET.Sdk.Web">



  <PropertyGroup>

    <RootNamespace>Aumbrye.Api</RootNamespace>

  </PropertyGroup>



  <ItemGroup>

    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />

    <PackageReference Include="AspNetCore.HealthChecks.Redis" />

    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />

    <PackageReference Include="Npgsql.OpenTelemetry" />

    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />

    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />

    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />

    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />

    <PackageReference Include="Swashbuckle.AspNetCore" />

  </ItemGroup>



  <ItemGroup>

    <ProjectReference Include="..\Aumbrye.Application\Aumbrye.Application.csproj" />

    <ProjectReference Include="..\Aumbrye.Infrastructure\Aumbrye.Infrastructure.csproj" />

    <ProjectReference Include="..\..\..\..\packages\shared\Aumbrye.Shared.csproj" />

    <ProjectReference Include="..\..\..\..\packages\procedural\Aumbrye.Procedural.csproj" />

  </ItemGroup>



</Project>

