<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Aumbrye.ProcgenCli</RootNamespace>
    <AssemblyName>procgen-cli</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\packages\procedural\Aumbrye.Procedural.csproj" />
  </ItemGroup>

</Project>
