"""Hand-picked shape and material for the items that have one.

Carried over from the first item atlas, which mapped these by hand before the sheet was rebuilt.
The name heuristics in item_icons.py are a good default across two hundred and sixty items, but
they cannot know that a castle chalice is a cup rather than a flask, or that the flame relic core
is an orb rather than a gem. Where an entry exists here it wins; everything else falls through to
the heuristics.

Shape names are the keys of item_icons.SHAPES, material names the keys of item_icons.RAMPS, with
"@slot" reserved for the dimmed empty-slot ramp.
"""

CURATED: dict[str, tuple[str, str]] = {
    "arcane_dust": ("pouch", "cathedral"),
    "blood_relic_stone": ("orb", "elixir"),
    "bloodlust": ("charm", "elixir"),
    "bloodlust_charm": ("charm", "elixir"),
    "castle_amulet": ("amulet", "castle"),
    "castle_banner": ("banner", "castle"),
    "castle_boots": ("boot", "castle"),
    "castle_buckler": ("shield", "castle"),
    "castle_chalice": ("chalice", "gold"),
    "castle_crown": ("crown", "gold"),
    "castle_gauntlets": ("glove", "castle"),
    "castle_helm": ("helm", "castle"),
    "castle_plate": ("cuirass", "castle"),
    "castle_ring": ("ring", "castle"),
    "castle_sword": ("sword", "castle"),
    "cathedral_arcane_staff": ("staff", "cathedral"),
    "cathedral_gloves": ("glove", "cathedral"),
    "cathedral_holy_charm": ("charm", "gold"),
    "cathedral_pilgrim_boots": ("boot", "cathedral"),
    "cathedral_sanctum_ring": ("ring", "cathedral"),
    "cathedral_shadow_cloak": ("cloak", "umbral"),
    "cathedral_shadow_dagger": ("dagger", "umbral"),
    "cathedral_warden_helm": ("helm", "cathedral"),
    "crystal_bow": ("bow_recurve", "crystal"),
    "crystal_frost_ring": ("ring", "crystal"),
    "crystal_prism_amulet": ("amulet", "crystal"),
    "crystal_shard_blade": ("sword", "crystal"),
    "dungeon_key": ("key", "gold"),
    "elixir_might": ("flask", "vault"),
    "elixir_vigor": ("flask", "mire"),
    "ember_gauntlets": ("glove", "vault"),
    "flame_relic_core": ("orb", "vault"),
    "flame_sword": ("sword", "vault"),
    "frost_amulet": ("amulet", "frozen"),
    "frost_crystal": ("gem", "frozen"),
    "frost_gauntlets": ("glove", "frozen"),
    "frost_glacier_sword": ("greatsword", "frozen"),
    "frost_ice_ring": ("ring", "frozen"),
    "frost_knight_helm": ("helm", "frozen"),
    "frost_knight_plate": ("cuirass", "frozen"),
    "frost_raider_boots": ("boot", "frozen"),
    "frost_relic_shard": ("gem", "frozen"),
    "frost_warlord_blade": ("greatsword", "frozen"),
    "gold_ring": ("ring", "gold"),
    "guard_spear": ("spear", "iron"),
    "health_potion": ("flask", "elixir"),
    "hunter_bow": ("bow_recurve", "swamp"),
    "iron_boots": ("boot", "iron"),
    "iron_gauntlets": ("glove", "iron"),
    "iron_helm": ("helm", "iron"),
    "iron_plate": ("cuirass", "iron"),
    "iron_scrap": ("scrap", "iron"),
    "iron_sword": ("sword", "iron"),
    "iron_will": ("charm", "iron"),
    "jade_amulet": ("amulet", "mire"),
    "knight_blade": ("sword", "iron"),
    "knight_relic": ("orb", "iron"),
    "mana_potion": ("flask", "crystal"),
    "mythic_aegis": ("shield", "prism"),
    "mythic_blade": ("greatsword", "prism"),
    "mythic_crown": ("crown", "prism"),
    "mythic_ring": ("ring", "prism"),
    "poison_relic_vial": ("flask", "swamp"),
    "relic_bloodstone": ("orb", "elixir"),
    "relic_flame_core": ("orb", "vault"),
    "relic_frost_shard": ("gem", "frozen"),
    "relic_poison_vial": ("flask", "swamp"),
    "relic_shadow_veil": ("veil", "umbral"),
    "relic_stone_heart": ("heart", "iron"),
    "relic_sun_medallion": ("medallion", "gold"),
    "relic_wind_charm": ("charm", "hollow"),
    "rogue_dagger": ("dagger", "iron"),
    "ruby_amulet": ("amulet", "elixir"),
    "sage_staff": ("staff", "cathedral"),
    "shadow_essence": ("pouch", "umbral"),
    "shadow_relic_veil": ("veil", "umbral"),
    "silver_ring": ("ring", "iron"),
    "skip_100_floors": ("token", "gold"),
    "skip_10_floors": ("token", "iron"),
    "skip_250_floors": ("token", "gold"),
    "skip_500_floors": ("token", "prism"),
    "skip_50_floors": ("token", "iron"),
    "slot/amulet": ("amulet", "@slot"),
    "slot/boots": ("boot", "@slot"),
    "slot/chest": ("cuirass", "@slot"),
    "slot/gloves": ("glove", "@slot"),
    "slot/helmet": ("helm", "@slot"),
    "slot/relic": ("orb", "@slot"),
    "slot/ring": ("ring", "@slot"),
    "slot/secondary": ("shield", "@slot"),
    "slot/weapon": ("sword", "@slot"),
    "stamina_potion": ("flask", "gold"),
    "steel_boots": ("boot", "iron"),
    "steel_gauntlets": ("glove", "iron"),
    "steel_helm": ("helm", "iron"),
    "steel_plate": ("cuirass", "iron"),
    "stone_relic_heart": ("heart", "iron"),
    "sun_relic_medallion": ("medallion", "gold"),
    "swamp_bog_boots": ("boot", "swamp"),
    "swamp_mire_charm": ("charm", "swamp"),
    "swamp_toxin_dagger": ("dagger", "swamp"),
    "swift_step": ("charm", "hollow"),
    "swift_step_charm": ("charm", "hollow"),
    "tide_boots": ("boot", "frozen"),
    "training_greatsword": ("greatsword", "iron"),
    "unique_crown_of_the_crystal_sovereign": ("crown", "crystal"),
    "unique_fen_widows_veil": ("veil", "swamp"),
    "unique_heirless_crown": ("crown", "castle"),
    "venom_dagger": ("dagger", "swamp"),
    "void_amulet": ("amulet", "umbral"),
    "war_hammer": ("hammer", "iron"),
    "wind_relic_charm": ("charm", "hollow"),
}
