/**
 * This file is generated by `npm run generate:api`.
 * Do not edit by hand.
 */
export interface paths {
  "/api/v1/auth/register": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        401: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/auth/refresh": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RefreshRequest"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        401: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/auth/logout": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LogoutRequest"];
        };
      };
      responses: {
        204: {
          content: never;
        };
        401: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/leaderboards": {
    get: {
      parameters: {
        query: {
          biomeId?: string;
          tier?: number;
          limit?: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["LeaderboardPageResponse"];
          };
        };
      };
    };
  };
  "/api/v1/saves/current": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["SaveResponse"];
          };
        };
        401: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/health": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    AuthResponse: {
      tokens?: components["schemas"]["AuthTokensResponse"] | null;
      user?: components["schemas"]["AuthUserResponse"] | null;
    };
    AuthTokensResponse: {
      accessToken?: string | null;
      refreshToken?: string | null;
      accessTokenExpiresAt?: string | null;
    };
    AuthUserResponse: {
      id?: string;
      email?: string | null;
    };
    ErrorResponse: {
      error?: string | null;
      detail?: string | null;
    };
    HealthResponse: {
      status?: string | null;
    };
    LeaderboardEntryResponse: {
      accountId?: string;
      displayName?: string | null;
      elapsedSeconds?: number;
      submittedAt?: string;
    };
    LeaderboardPageResponse: {
      biomeId?: string | null;
      tier?: number;
      entries?: components["schemas"]["LeaderboardEntryResponse"][] | null;
    };
    LoginRequest: {
      email?: string | null;
      password?: string | null;
    };
    LogoutRequest: {
      refreshToken?: string | null;
    };
    RefreshRequest: {
      refreshToken?: string | null;
    };
    RegisterRequest: {
      email?: string | null;
      password?: string | null;
    };
    SaveResponse: {
      stateJson?: string | null;
      updatedAt?: string;
    };
  };
}

export type AuthResponse = components["schemas"]["AuthResponse"];
export type AuthTokensResponse = components["schemas"]["AuthTokensResponse"];
export type LeaderboardPageResponse = components["schemas"]["LeaderboardPageResponse"];
export type SaveResponse = components["schemas"]["SaveResponse"];
